version = 1

test_patterns = [
    "*/tests/**",
    "*/test_*.py"
]

exclude_patterns = [
    "docs/**",
    "ci/**"
    "versioneer.py"
    "_version.py"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
