name: py3dep
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - owslib
  - requests
  - xarray
  - scipy
  - rasterio
  - shapely
  - pyproj

  - dask
  - netCDF4
  - bottleneck

  - bump2version
  - pytest-cov
  - pytest-xdist
  - pre-commit
  - codecov
  - coverage

  - recommonmark
  - nbsphinx
  - sphinx
  - sphinx-copybutton
  - pycodestyle
  - numpydoc

  - beautifulsoup4
  - python-slugify
  - css-html-js-minify
  - unidecode
  - pip:
    - nbsphinx_link
    - git+https://github.com/bashtage/sphinx-material.git
